### ISSUE TITLE
Console error log when perform a search

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#187] opened 2016-04-10 20:11 UTC
Environment

Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Mouse over search icon glass.

3) Set the characters "#" in search field and press enter.

4) Open Firebug tools and see the calls.

actual: 200 Aborted error message is different.

expected: do not display this error.

see attach!
![error](https://cloud.githubusercontent.com/assets/18361424/14412723/5c3da8d8-ff71-11e5-95cd-ad51031f183f.png)

Notes

- this error appear when use the "#" character!

![error](https://cloud.githubusercontent.com/assets/18361424/14412729/80d4c2d0-ff71-11e5-83c6-85824f3e9017.png)

**Comment by callmekatootie** [comment] 2016-04-13 04:53
@fnisen @nlitwin Bug?

**Comment by nlitwin** [comment] 2016-04-13 04:55
This is a duplicate of the bug that special characters in the URL are not working.

**Closed** 2016-04-13 05:13 UTC
Labels: help wanted

**Comment by onetliviunicu** [comment] 2016-04-13 07:11
hy, is this issue can be resolved by other, for testing a separate test was performed, can you please review again?

**Comment by callmekatootie** [comment] 2016-04-13 12:44
Duplicate of https://github.com/appirio-tech/topcoder-app-r/issues/53

**Comment by onetliviunicu** [comment] 2016-04-13 12:49
Why are considered duplicate?The test was performed and the case is different?

**Comment by callmekatootie** [comment] 2016-04-13 12:53
You are searching with the special character '#'
