### ISSUE TITLE
Search icon is too small and non-obvious in desktop mode

### ISSUE THREAD

**Issue by Colinh84** [appirio-tech/topcoder-app-r#107] opened 2016-04-09 08:03 UTC
Search icon is displayed at the very far right-hand side of the browser window in full-screen dsktop mode and is very small, making it not obvious that this is where we have to go to search for members.

Expected: 
Search icon should be in a place that is easy to see, and be a bit bigger to match the style of the rest of the page.

Actual:
Search icon is out of the way and hard to find.

Screenshot: http://i.imgur.com/DEqdWsi.png

**Requirements**
- [ ] Please adhere to the code style specified in the readme.
- [ ] Make sure the component is rendered correctly on all screen sizes as specified in the designs

**Comment by callmekatootie** [comment] 2016-04-12 10:52
Not sure if bug @fnisen @nlitwin

**Comment by nlitwin** [comment] 2016-04-12 17:23
This isn't a bug. We don't plan on changing the old nav because we are coming out with an entirely new one in the near future. We forgot to mention in the challenge description that we didn't want the old navigation to be part of the bug hunt, but we are accepting valid bugs with it to be fair.

**Comment by fnisen** [comment] 2016-04-13 03:36
Yeah, this is poor design that will be fixed, but not a bug.

**Closed by fnisen** 2016-04-13 03:36 UTC
Labels: help wanted
