### ISSUE TITLE
Load More button available even nine results

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#198] opened 2016-04-10 21:04 UTC
Environment

Firebug
Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Mouse over search icon glass.

3) Complete search field with text "339".

4) Press enter.

actual: Load More button is available even End of results.

expected: do not display Load More button when 9 results are displayed.

see attach!

![load-more_001](https://cloud.githubusercontent.com/assets/18361424/14413088/fe14adc6-ff78-11e5-94e4-8ac2a1dad615.png)

**Comment by nlitwin** [comment] 2016-04-18 23:24
Exact duplicate of https://github.com/appirio-tech/topcoder-app-r/issues/43, even the search term is the same.

**Closed** 2016-04-18 23:29 UTC
Labels: bug, duplicate
