### ISSUE TITLE
No max number of characters set  in fields

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#75] opened 2016-04-09 07:23 UTC
Environment

Chrome 47.0.2526.73

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Press on the search icon glass from the top right of page.

3) Enter a long character in search field(ex: abcdefghijklss.........).

actual: any long character letter can be set in field.

expected: allow only letter with a max of 50 characters.

see attach!

![max-number](https://cloud.githubusercontent.com/assets/18361424/14402393/096fb388-fe3d-11e5-82c4-522b8142d497.png)

**Comment by callmekatootie** [comment] 2016-04-12 06:03
Duplicate of #71

**Closed by callmekatootie** 2016-04-12 06:03 UTC
