### ISSUE TITLE
Invalid results for search criteria

### ISSUE THREAD

**Issue by onetliviunicu** [appirio-tech/topcoder-app-r#189] opened 2016-04-10 20:24 UTC
Environment

Mozilla Firefox 45.0.1
Chrome 49.0.2623.112
Windows 7

Description

1) Login into application https://www.topcoder-qa.com/search/members/?q=javascript.

2) Mouse over search icon glass.

3) Complete search field with "a|a".

4) Press enter to perform the search.

actual: Oops! There was an error.

expected: do not display the error page because this can be a valid username.

see attach!

![text](https://cloud.githubusercontent.com/assets/18361424/14412808/6a778458-ff73-11e5-8c88-a8c811c6618e.png)

**Comment by callmekatootie** [comment] 2016-04-13 04:56
@fnisen @nlitwin I am not sure if this user exists but the participant says so - a|a

I tried searching in the old site as well but it showed up no results.

**Comment by nlitwin** [comment] 2016-04-13 04:58
This is a duplicate of the bug that special characters in the URL do not work.

**Closed** 2016-04-13 05:16 UTC
Labels: duplicate

**Comment by onetliviunicu** [comment] 2016-04-13 15:40
This text "a|a" can be considered as special characters?

**Comment by nlitwin** [comment] 2016-04-13 16:13
On my screen, the character between the two a's looks like a pipe character, not a lowercase L. I copied and pasted it in an encoder and it comes out as %7C, which is the vertical bar / pipe character.

**Comment by onetliviunicu** [comment] 2016-04-14 08:04
ok, thank you!
