### ISSUE TITLE
Blank feedback can be submitted

### ISSUE THREAD

**Issue by madhusaha26** [appirio-tech/topcoder-app-r#42] opened 2016-04-09 06:37 UTC
Steps
1. Open the page
2. Click UserSnap
3.Enter space
4. Submit
5. Feedback gets submitted

Actual Results:
Blank feedback can be submitted

Expected Results:
Blank feedback should not be allowed

**Comment by callmekatootie** [comment] 2016-04-12 05:29
Not sure I understand the issue - if you mean that the user can enter empty search string, then it's a duplicate of #22

**Closed by callmekatootie** 2016-04-12 05:29 UTC

**Comment by nlitwin** [comment] 2016-04-12 07:20
I think madhusaha26 means the Feedback icon in the lower right of the screen, but this is not part of the new page.

![image](https://cloud.githubusercontent.com/assets/5829188/14452565/4f0df6d0-0044-11e6-90f6-d16b2201f27f.png)
