### ISSUE TITLE
should not allow input blank strings in the text box

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/topcoder-app-r#61] opened 2016-04-09 07:06 UTC
Mac 10.11.4 + Chrome 49.0

1. open https://www.topcoder-qa.com/search/members/?q=javascript
2. click the search button
3. enter some spaces in the text box, click Enter key

expected: it should show some validation error for the user that the blank strings are not allowed to search

actual: not such message shown

![qq20160409-31 2x](https://cloud.githubusercontent.com/assets/4590317/14402320/bc7c5252-fe64-11e5-88a7-0146c8608724.png)

**Comment by callmekatootie** [comment] 2016-04-12 05:48
Duplicate of #22

**Closed by callmekatootie** 2016-04-12 05:48 UTC
